/**
 * Game UI Components - Barrel Export
 * Centralized export for all game-style UI components
 */

export { default as GameButton } from './GameButton.vue'
export { default as GameButtonGroup } from './GameButtonGroup.vue'
export { default as GameIcon } from './GameIcon.vue'
export { default as GameTag } from './GameTag.vue'
export { default as GameDivider } from './GameDivider.vue'
export { default as GameTabs } from './GameTabs.vue'
export { default as GameTabPane } from './GameTabPane.vue'
export { default as GameInput } from './GameInput.vue'
export { default as GameTextarea } from './GameTextarea.vue'
export { default as GameUpload } from './GameUpload.vue'
export { default as GameSwitch } from './GameSwitch.vue'
export { default as GameSelect } from './GameSelect.vue'
export { default as GameCard } from './GameCard.vue'
export { default as GamePageContainer } from './GamePageContainer.vue'
export { default as GameLayout } from './GameLayout.vue'
export { default as GameSection } from './GameSection.vue'
export { default as HeroSection } from './HeroSection.vue'
export { default as GameTable } from './GameTable.vue'
export { default as GameBlock } from './GameBlock.vue'
export { default as GameCollapseToggle } from './GameCollapseToggle.vue'
export { default as GameSubBlock } from './GameSubBlock.vue'
export { default as GameCodeQuote } from './GameCodeQuote.vue'
export { default as GameIconButton } from './GameIconButton.vue'

// Type exports
export type { GameButtonProps, GameButtonEmits } from './GameButton.types'
export type { GameInputProps, GameInputEmits } from './GameInput.types'
export type { GameSelectProps, GameSelectEmits, GameSelectOption } from './GameSelect.types'
export type { GameTextareaProps, GameTextareaEmits } from './GameTextarea.types'
export type { GameSwitchProps, GameSwitchEmits } from './GameSwitch.types'
export type { GameUploadProps, GameUploadEmits } from './GameUpload.types'
export type { GameIconButtonProps, GameIconButtonEmits } from './GameIconButton.types'
export type { GameTagProps, GameTagEmits } from './GameTag.types'
export type { GameCardProps, GameCardEmits } from './GameCard.types'
export type { GameBlockProps, GameBlockEmits } from './GameBlock.types'